### ISSUE TITLE
Unexpected container CPU usage values

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/executor#30]
We are currently on diego 1.25.3 and garden-runc 1.9.3 and we notice that sometimes the container metrics contain CPU usage values in excess (> 800%) of the number of available cores (8):

![image](https://user-images.githubusercontent.com/408018/38285491-6439d970-37fb-11e8-897c-85effc973995.png)

(this is the graph over time of the raw CPU usage container metric; values over 800% should be impossible)

Similar data is reported also by the CF CLI, so it's not a visualization issue:

```
cf app myapp                            
Showing health and status for app myapp in org myorg / space myspace as someuser...

name:              myapp
requested state:   started
instances:         1/1
usage:             2G x 1 instances
routes:            someroute.local
last uploaded:     Mon 18 Dec 14:31:27 JST 2017
stack:             cflinuxfs2
buildpack:         https://github.com/cloudfoundry/java-buildpack.git

     state     since                  cpu      memory       disk           details
#0   running   2018-04-03T08:39:54Z   821.7%   1.2G of 2G   203.5M of 1G
```

According to the code this shouldn't be possible: https://github.com/cloudfoundry/executor/blob/43ab01d775d6de766eb90cce4169c9d89028645f/containermetrics/stats_reporter.go#L199-L206

**Comment by CAFxX** [comment]
> Also, I think we've realized for quite a while that these CPU metrics are often not particularly useful in isolation, so if you have thoughts on additional or alternative CPU-usage metrics to help put them into context for app developers or platform operators, I'd certainly appreciate hearing them (as would @julz and @aHev, I suspect).

I pitched some ideas [a while back](https://github.com/cloudfoundry/cli/issues/1194). There was some form of agreement that the current state is not ideal, but not enough consensus to move forward.

**Comment by goonzoid** [comment]
Hey @CAFxX, quick question: do you have `diego.executor.container_metrics_report_interval` set in this environment, and if so, what is it set to?

Thanks!

**Comment by CAFxX** [comment]
@goonzoid we have it set to `2s`

**Comment by flawedmatrix** [comment]
Hi @CAFxX, we have discovered the root cause in this story: https://www.pivotaltracker.com/story/show/156491008

In short, the current implementation of the way the executor collects metrics introduces a nontrivial (possibly 5s, depending on number of containers on the cell and CPU load) delay that could contribute extra time to `timeSpentB` in the CPU percentage calculation.

To alleviate this issue for the meantime, is it possible to increase your  `diego.executor.container_metrics_report_interval` to a higher value? I concede that the calculation for CPU usages would still be inaccurate, but would at least be less likely to reach shockingly high values.

For the future, I believe we on the Diego team would need to work with the Garden team to see how we can resolve this issue in the future and work out a better user experience for understanding app resource usage.

**Comment by CAFxX** [comment]
We can raise it temporarily, although this will cause some pain to our users that have custom monitoring systems using container metrics as one of their sources. 

Just as a data point, our cells have ~7.5 instances running on average. We don't use hard caps, but I would expect that load generated inside containers shouldn't negatively impact the functionality of rep/garden.
