### ISSUE TITLE
Why do non-cacheable blobs fail?

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/executor#31]
Hi,
I'm part of the [CF Bits-Service](https://github.com/cloudfoundry-incubator/bits-service-release) team. We're implementing a local blobstore that replaces the one in CC. We noticed that blob responses must contain either an `ETag` or `Last-Modified` header, otherwise the Executor won't accept it, because the [CachedDownloader treats it as `NotCacheable`](https://github.com/cloudfoundry/cacheddownloader/blob/34f4570d8caa409f4d81dd1ee4360d1a3a9caf90/cached_downloader.go#L88-L90) and [Executor treats that as non-recoverable error](https://github.com/cloudfoundry/executor/blob/3db3aa5a8293988781e799b4062e19c23eb5f850/depot/containerstore/dependencymanager.go#L102-L116).

Is there a specific reason why non-cacheable blobs fail? If so, could you please explain?

We can add this header, but it came with a big surprise and was also very hard to track down, because from the error message
`{"timestamp":"1524044759.316318274","source":"rep","message":"rep.executing-container-operation.task-processor.run-container.containerstore-create.node-create.failed-fetching-cache-dependency","log_level":2,"data":{"cache-key":"91fd...2288","container-guid":"b95....59","container-state":"reserved","download-url":"https://bits-service.service.cf.internal/buildpacks/91f....b46e2288","error":"Not cacheable directory","guid":"b9516b72-5b31-460d-bc34-2d9af6437759","session":"96.1.3.2.1"}}`
it's not obvious what's wrong.

Any thoughts are appreciated.

Thanks,
Peter and the Bits team

/cc @suhlig @idev4u @smoser-ibm @eric-cartman

**Comment by jvshahid** [comment]
For context, this change/feature was introduced in [#108774976](https://www.pivotaltracker.com/stories/show/108774976) and the acceptance criteria is very explicit about the behavior. The `ETag` is required in order to invalidate the cached data (based on the story description). **Note** this is only the case when the [FetchAsDirectory](https://github.com/cloudfoundry/cacheddownloader/blob/master/cached_downloader.go#L244) is called. That said, we could do something similar to [Fetch](https://github.com/cloudfoundry/cacheddownloader/blob/master/cached_downloader.go#L185) to allow users of the cacheddownloader to download a directory temporarily. I'll let @emalm comment on this idea and the original acceptance criteria of the story mentioned above.

@petergtz what exactly is the use case for this ? `ETag` and `Last-Modified` are critical to the operation of the [cacheddownloader](https://github.com/cloudfoundry/cacheddownloader/). It allows multiple containers to share those assets while making it possible to invalidate the data when it change. As I mentioned before, we could modify `FetchAsDirectory` to allow this use case, but I would be interested in justifying that change.

**Comment by petergtz** [comment]
@jvshahid Thanks for getting back to me on this and sharing your thougths and the context of this feature.

First, please note that we did implement caching in our implementation since I asked my questions above, and hence made it compatible with the cacheddownloader. All of the below is for me to better understand why things are the way they are.

> `ETag` and `Last-Modified` are critical to the operation of the cacheddownloader.

This is clear. My question about it is not so much *how*, but rather *why* must artifacts used by the Executor be cacheable? While this is a very much desirable feature, it seems to be a performance optimization. But why is it required then? The executor could accept non-cacheable blobs and spit out a warning or info in the log.

My other comment was about the error reporting around this cacheability. `"Not cacheable directory"` is not very instructive in telling me that an `ETag` or `Last-Modified` header is missing. An error message like `"Not cacheable directory. ETag and Last-Modified header missing in HTTP response"` would have helped a lot in tracking down what's wrong.

**Comment by petergtz** [comment]
@jvshahid 

> ...
> That said, I don't see an argument to change this behavior.

Sure. Make sense.

> would changing the error message be sufficient to address this github issue ?

That would be awesome, yes (in the interest of anyone stumbling up on this in the future).

I could imagine that the error in the log should say something similar to the following, instead of just `Not cacheable directory`:
- [`Not cacheable directory (no ETag and no Last-Modified header was found in response)`](https://github.com/cloudfoundry/cacheddownloader/blob/34f4570d8caa409f4d81dd1ee4360d1a3a9caf90/cached_downloader.go#L284-L292)
- [`Not cacheable directory (cache key is missing)`](https://github.com/cloudfoundry/cacheddownloader/blob/34f4570d8caa409f4d81dd1ee4360d1a3a9caf90/cached_downloader.go#L245-L247)

Separating those 2 error conditions and describing them in that detail would point immediately to the issue.

Thanks
