### ISSUE TITLE
No module go-control-plane/pkg/util

### ISSUE THREAD

**Issue by WalterS** [cloudfoundry/executor#51]
When I run go mod vendor, I get 'go-control-plane@latest found (v0.9.1), but does not contain package github.com/envoyproxy/go-control-plane/pkg/util'
```# go mod vendor
code.cloudfoundry.org/executor/depot/containerstore imports
github.com/envoyproxy/go-control-plane/pkg/util: module github.com/envoyproxy/go-control-plane@latest found (v0.9.1), but does not contain package github.com/envoyproxy/go-control-plane/pkg/util
```
The module is referenced [here](https://github.com/cloudfoundry/executor/blob/0e866bf437f106d3744adc104d2ad6dd4c2a2359/depot/containerstore/proxy_config_handler.go#L28) and [here](https://github.com/cloudfoundry/executor/blob/0e866bf437f106d3744adc104d2ad6dd4c2a2359/depot/containerstore/proxy_config_handler_test.go#L29).

**Comment by WalterS** [comment]
The code in go-control-plane has changed on 11 September: https://github.com/envoyproxy/go-control-plane/commit/52b167a709f111e6298136064bbaae43419ab22f#diff-b1deaf5bd12b77f57041cd8d3eeca40c

**Comment by sunjayBhatia** [comment]
@WalterS we have not converted Diego libraries to Go modules yet. We are still using [diego-release](https://github.com/cloudfoundry/diego-release) as a `GOPATH` and some dependencies may be out of date, so in order to get the dependencies at the correct versions, you will need to work with `executor` within `diego-release`.

We will likely be converting our codebases to Go modules soon, so stay tuned.
